### ISSUE TITLE
Just a question

### ISSUE THREAD

**Issue by UnknownPear** [ChrisChalms/DialogueSystem#2] opened 2022-12-15 21:21 UTC
HI! This system is amazing and Im having a great time using it, im wondering if theres a way I can change this dynamically, for example the theme, if I wanted to change the theme in any conversation to dark  when its night time, how would I accomplish that?

**Comment by ChrisChalms** [comment] 2022-12-15 22:12
Hi, I'm glad you're enjoying it! Theme swapping is supported, and it's quite easy to implement. There's a video showcasing it [here](https://youtu.be/EemidLV_zkw). You just need to create a theme asset, assign it to the theme repo, which allows you to either change it through conversations using actions, or with the "theme" tag on a given conversation. 

You can see examples in the ExampleScene->Conversations->DialogueFiles->TestingConversation. The conversation with the Id of 1 starts with the theme set to default, then changes it using an action

**Closed as completed** 2022-12-15 22:13 UTC

**Comment by UnknownPear** [comment] 2022-12-16 05:56
Thanks for the response! I know about that, but the "issue" is that I can only change it in a conversation where its predetermined, wouldn't there be a way to change it through code? Because what I'm trying to do is: if the game manager says is night, it'll change the theme to dark, and when its day back to light. Things i'm able to do following that same logic is: when the game manager says its raining all I simply do is register the variable repo to a bool (conversationRaining) using another script and then the dialogue controller picks that up and moves to the id where that bool is true

**Comment by ChrisChalms** [comment] 2022-12-16 06:07
My bad. Right now there's no way to call conversation actions through code, it's been one thing I've thought about changing for the next version. But what you could do in the meantime is create a DialogueAction class object, cache it somewhere, and add it to the list of a conversation's Actions when it's loaded/used. Then it could be called by your game manager can run it via the ActionController.

Edit: I should say, there's no nice way to call actions from code

**Comment by ChrisChalms** [comment] 2022-12-16 06:58
After having a quick look and reminding myself how it all works, it's probably easier to use the DialogueController.ChangeTheme method, instead of using a cached Action

**Comment by UnknownPear** [comment] 2022-12-16 15:28
That worked! I didn't even notice there was a changetheme variable in the controller, my bad. Thanks for your help! And also, do you plan to update the system more? And if so what are you planning to add?

**Comment by UnknownPear** [comment] 2022-12-17 22:37
Hi, I just discovered a bug that makes me unable to trigger different conversations with other npcs, then I register the bools I do it through code and initialize them on a start method like this: 
 ```
if (draxFirstConversation)
        {
            VariableRepo.Instance.Register("draxFirstConversation", true);
        }
        else
        {
            VariableRepo.Instance.Register("draxFirstConversation", false);

        }
```

the issue is that all npcs get overwritten with the conversation that the boolean defined true, why isnt the conversation being loaded based on the actual file that already is getting passed in?

**Comment by ChrisChalms** [comment] 2022-12-17 22:48
Hi, I'm not quite sure I follow. You have multiple conversations loaded into the conversation repo, but when you register the variable `VariableRepo.Instance.Register("draxFirstConversation", draxFirstConversation);`, those conversations get overridden?

**Comment by UnknownPear** [comment] 2022-12-17 22:56
Exactly, when I register through code all conversations just lead to that conversation that was registered, im only using it though code because I need to keep track of the bools so I can use it in my save system. I debug logged the conversation being loaded when the player interacts with the npc and the file is the correct one but not displaying it

**Comment by ChrisChalms** [comment] 2022-12-17 23:18
Thanks for bringing it to my attention, I'll investigate it later today. I suspect it's a pretty easy fix. Would you mind giving me your conversation JSON files so I can test it with your starting conditions? Feel free to take out all the game's dialogue.

**Comment by UnknownPear** [comment] 2022-12-17 23:27
Appreciate it! https://easyupload.io/gfygao here you go

**Comment by ChrisChalms** [comment] 2022-12-18 02:32
I've had a quick look at the files you've sent, and it's behaving as expected on my end. I think the issue is that in both JSON files you have a conversation node, with the id of 18, that's the same. So when the variable `draxFirstConversation` is changed both conversations say the same thing. I've modified node 18 to show the "Drax" and "Old Man In Cave" in [these files](https://easyupload.io/), and everything appears to be working normally.

**Comment by UnknownPear** [comment] 2023-10-20 02:04
Hey, sorry, was my error, forgot to update you! Appreciate the attention as well, was wondering of theres a way to cast variables in the json, for example <sendmessage=DialogueController>RegisterVariableToRepo(convo1, true)</sendmessage>.
Thanks!
